name: animated_responsive_layout
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
  - assets/images/avatar_1.png
  - assets/images/avatar_2.png
  - assets/images/avatar_3.png
  - assets/images/avatar_4.png
  - assets/images/avatar_5.png
  - assets/images/avatar_6.png
  - assets/images/avatar_7.png
  - assets/images/thumbnail_1.png
                               